# Criação de Vetores e Arrays em Numpy

In [3]:
import numpy as np 

In [6]:
np

<module 'numpy' from '/opt/anaconda3/lib/python3.12/site-packages/numpy/__init__.py'>

In [8]:
minha_lista = [1,2,3]

In [10]:
np.array(minha_lista)

array([1, 2, 3])

In [12]:
minha_matriz = [[1,2,3], [4,5,6]]

In [14]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
sum(minha_lista) # não funciona para matriz 

6

In [18]:
matriz_np = np.array(minha_matriz) 

In [22]:
np.sum(matriz_np) # somando itens da matriz com numpy

21

## Criando um array de elementos dentro do range

In [25]:
np.arange(0, 10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(0,10,2) # criando sequencia ate o 10 indo de 2 em 2

array([0, 2, 4, 6, 8])

## Arrays com 0

In [30]:
np.zeros(3) # Criando array com 3 zeros

array([0., 0., 0.])

In [32]:
np.zeros([3,5]) # criando matriz com 3 linhas e 5 colunas

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.zeros([3,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## Criando matriz com 1

In [37]:
np.ones(3)

array([1., 1., 1.])

In [39]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [41]:
np.ones([4,4,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

## Criando a matriz identidade

In [44]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Criando uma sequência de valores contínua igualmente espaçadas

In [47]:
np.linspace(0, 100, 50)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

## Valores aleatorios entre 0 e 1

In [52]:
np.random.random(5) * 100

array([60.17509466, 43.27402008, 41.84059629, 42.60979149, 18.90268918])

In [54]:
np.random.random([2, 5]) * 100 # Gera um array de 2 linhas 5 colunas com um intervalo de 0 a 100

array([[17.54954848, 14.0376213 , 30.26764008,  9.46831335, 64.21665678],
       [40.30105362, 25.79570673, 96.55667436,  3.47917535, 21.90708921]])

## Método reshape

In [57]:
np.zeros(4)

array([0., 0., 0., 0.])

In [59]:
array = np.zeros(4)

In [61]:
array

array([0., 0., 0., 0.])

In [65]:
array.shape

(4,)

In [69]:
array.reshape([2, 2]) 

array([[0., 0.],
       [0., 0.]])